"""Single config schema for bases, tasks, LoRA settings, training settings, runs and experiments.

Every experiment is launchable from YAML/JSON config files (spec §13). Config files may
reference other config files by path (relative to the repository root or to the referring
file); :func:`load_config` resolves them into typed dataclasses and validates them.
"""

from __future__ import annotations

import dataclasses
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]

CANONICAL_MODULES = ("q", "k", "v", "o", "up", "down", "gate")


class ConfigError(ValueError):
    """Raised when a config file is malformed or violates a protocol requirement."""


# ---------------------------------------------------------------------------
# Typed config objects
# ---------------------------------------------------------------------------


@dataclass
class BaseConfig:
    """A frozen base model checkpoint.

    ``source`` is ``hub`` (Hugging Face hub id + immutable revision), ``local`` (a directory
    with a saved checkpoint) or ``tiny`` (a randomly initialised miniature model built by
    :mod:`uag.tiny` for smoke tests; ``tiny_spec`` describes it).
    """

    name: str
    model_id: str
    source: str = "hub"
    revision: str | None = None
    tokenizer_id: str | None = None
    tokenizer_revision: str | None = None
    family: str = ""
    role: str = ""  # A1 / A2 / B / C
    dtype: str = "bfloat16"
    tiny_spec: dict[str, Any] | None = None
    notes: str = ""

    def validate(self, require_pinned: bool = False) -> None:
        if self.source not in {"hub", "local", "tiny"}:
            raise ConfigError(f"base {self.name}: unknown source {self.source!r}")
        if self.source == "tiny" and not self.tiny_spec:
            raise ConfigError(f"base {self.name}: tiny bases need a tiny_spec")
        if require_pinned and self.source == "hub" and not is_pinned_revision(self.revision):
            raise ConfigError(
                f"base {self.name}: revision must be an immutable commit hash for this "
                f"experiment (got {self.revision!r}). Pin it before launching."
            )
        if not self.family:
            raise ConfigError(f"base {self.name}: family is required (used for heterogeneity tests)")

    @property
    def pinned(self) -> bool:
        return self.source != "hub" or is_pinned_revision(self.revision)


def is_pinned_revision(rev: str | None) -> bool:
    """A pinned revision is a full 40-hex-char git commit hash."""
    if not rev or len(rev) != 40:
        return False
    return all(c in "0123456789abcdef" for c in rev.lower())


@dataclass
class TaskConfig:
    """A controlled transformation with a deterministic generator and a scalar primary metric."""

    task_id: str
    name: str
    generator: str
    task_class: str
    metric: str
    version: int = 1
    generator_version: str = "1"
    metric_direction: str = "higher"
    scoring: str = "generate"  # generate | choices
    n_train: int = 2000
    n_valid: int = 200
    n_test: int = 500
    seed: int = 0
    prompt_template_version: str = "v1"
    max_new_tokens: int = 64
    generator_kwargs: dict[str, Any] = field(default_factory=dict)
    metric_kwargs: dict[str, Any] = field(default_factory=dict)
    # Stage 3: independently measured factor metrics, e.g. {arithmetic: exact_number}
    factor_metrics: dict[str, str] = field(default_factory=dict)
    license: str = "CC0-1.0 (deterministically generated by uag)"
    contamination_notes: str = "Synthetic, rule-generated; no public benchmark text."

    def validate(self) -> None:
        if self.metric_direction not in {"higher", "lower"}:
            raise ConfigError(f"task {self.task_id}: metric_direction must be higher|lower")
        if self.scoring not in {"generate", "choices"}:
            raise ConfigError(f"task {self.task_id}: scoring must be generate|choices")
        for n in ("n_train", "n_valid", "n_test"):
            if getattr(self, n) <= 0:
                raise ConfigError(f"task {self.task_id}: {n} must be positive")

    @property
    def dataset_key(self) -> str:
        return f"{self.task_id}.v{self.version}"


@dataclass
class LoraSettings:
    rank: int = 16
    alpha: float = 32.0
    dropout: float = 0.0
    target_modules: list[str] = field(default_factory=lambda: list(CANONICAL_MODULES))
    use_rslora: bool = False
    # Which RNG draws the random LoRA A init: "seed" = the run seed alone (every task on a base
    # shares A0 for a given seed), "task" = derived from (task, seed) so tasks get independent
    # inits, "base" = derived from the base name only (one A per base, for every task and seed).
    init_seed_scope: str = "seed"
    # False = LoRA-FA style: A stays frozen at its init and only B trains. With
    # init_seed_scope: base, every adapter of a base then shares one fixed input basis A_m, and
    # a task is fully described by its B (the v2 dry run showed trained A moves only 4-22% anyway).
    train_A: bool = True
    # How the fixed A is chosen (uag.eyes): random (PEFT default), whitened (random after
    # equalising input-direction variances) or pca (top input directions), from generic
    # calibration text (wikitext, or builtin for offline/tests). Data-informed eyes need one A
    # per base (init_seed_scope: base).
    a_init: str = "random"
    a_calibration: str = "wikitext"
    a_calibration_tokens: int = 32768

    def validate(self) -> None:
        if self.a_init not in {"random", "whitened", "pca"}:
            raise ConfigError("LoRA a_init must be random|whitened|pca")
        if self.a_init != "random" and self.init_seed_scope != "base":
            raise ConfigError("a_init whitened/pca needs init_seed_scope: base (one A per base)")
        if self.init_seed_scope not in {"seed", "task", "base"}:
            raise ConfigError("LoRA init_seed_scope must be seed|task|base")
        if not self.train_A and self.init_seed_scope != "base":
            raise ConfigError("train_A: false needs init_seed_scope: base (one fixed A per base)")
        bad = [m for m in self.target_modules if m not in CANONICAL_MODULES]
        if bad:
            raise ConfigError(
                f"LoRA target_modules must be canonical classes {CANONICAL_MODULES}, got {bad}"
            )
        if self.rank <= 0:
            raise ConfigError("LoRA rank must be positive")

    @property
    def scaling(self) -> float:
        return self.alpha / (self.rank**0.5) if self.use_rslora else self.alpha / self.rank


@dataclass
class TrainSettings:
    learning_rate: float = 2e-4
    weight_decay: float = 0.0
    batch_size: int = 8
    grad_accum: int = 1
    max_tokens_seen: int = 2_000_000
    max_seq_len: int = 512
    warmup_ratio: float = 0.03
    eval_every_steps: int = 100
    selection_metric: str = "valid_loss"  # valid_loss | valid_primary
    valid_max_examples: int = 200
    optimizer: str = "adamw"
    dtype: str = "bfloat16"
    deterministic: bool = True
    device: str = "auto"
    gradient_checkpointing: bool = False  # trades ~30% speed for much less activation memory
    # Early stopping on ``selection_metric``: stop after this many consecutive validation
    # evaluations without an improvement larger than ``early_stopping_min_delta``, but never
    # before ``min_steps``. 0 disables it; ``max_tokens_seen`` is then the fixed budget, and
    # with early stopping it is the cap. The selected checkpoint is always the best one.
    early_stopping_patience: int = 0
    early_stopping_min_delta: float = 0.0
    min_steps: int = 0
    max_wall_minutes: float | None = None  # hard time limit (GPU benchmark only)
    # Early stopping is not allowed before this many passes over the training split (on top of
    # min_steps): tasks such as T1/T2 sit at chance for a while before they take off.
    min_epochs: float = 0.0
    # Per-task token caps (set from pilot learning curves, `uag learning-curves`). A task's cap
    # is the same for every base, so budgets stay identical across bases; tasks not listed use
    # max_tokens_seen.
    max_tokens_by_task: dict[str, int] = field(default_factory=dict)

    def token_cap(self, task_id: str) -> int:
        return int(self.max_tokens_by_task.get(task_id, self.max_tokens_seen))

    def validate(self) -> None:
        if self.selection_metric not in {"valid_loss", "valid_primary"}:
            raise ConfigError("selection_metric must be valid_loss|valid_primary")
        if self.early_stopping_patience < 0 or self.min_steps < 0:
            raise ConfigError("early_stopping_patience and min_steps must be >= 0")
        if self.optimizer != "adamw":
            raise ConfigError("only adamw is implemented")


@dataclass
class MapSettings:
    """Pair-map fitting settings (spec §5.4)."""

    methods: list[str] = field(
        default_factory=lambda: ["svd_procrustes", "svd_linear", "identity", "cross_lora", "random"]
    )
    k: int = 32  # truncated-SVD coordinate dimension
    ridge: float = 1e-2
    als_iters: int = 50
    layer_matching: str = "relative_depth"


@dataclass
class HoldoutSplitSpec:
    split_id: str
    holdout: list[str]


@dataclass
class FewShotSettings:
    """Few-shot base evaluation: k worked training examples in the prompt (deterministic)."""

    k: int = 5
    seed: int = 0


@dataclass
class GateSettings:
    """Pre-declared Stage-0 gate (spec §5.6). Fixed before held-out tests are run."""

    primary_method: str = "svd_procrustes"  # the learned map the gate is evaluated on (no post-hoc pick)
    # Reference score S_base for lift, eligibility and RecoveredLift: the few-shot base (so that
    # an adapter only gets credit for what k demonstrations of the output format cannot give)
    # or the zero-shot base. The other one is still evaluated and reported.
    baseline: str = "fewshot"  # fewshot | zeroshot
    min_heterogeneous_pairs: int = 2
    min_median_recovered_lift: float = 0.30
    min_direct_lift: float = 0.05  # cells with smaller direct-LoRA lift are ineligible
    learned_methods: list[str] = field(default_factory=lambda: ["svd_procrustes", "svd_linear"])
    non_learned_baselines: list[str] = field(default_factory=lambda: ["identity", "cross_lora", "random"])
    # Criterion 4 (optional): on the graded measure (`uag graded-transfer`, gold-answer NLL), the
    # primary method's RecoveredNLL beats the strongest non-learned baseline with a paired
    # bootstrap CI excluding zero. Catches transfer that all-or-nothing task metrics miss, and
    # (with target_mean as a baseline) whether anything source-specific transfers at all.
    graded_beats_baselines: bool = False
    bootstrap_samples: int = 2000
    ci_level: float = 0.95
    seed: int = 0


@dataclass
class ExperimentConfig:
    name: str
    bases: list[BaseConfig]
    tasks: list[TaskConfig]
    lora: LoraSettings
    train: TrainSettings
    seeds: list[int]
    splits: list[HoldoutSplitSpec] = field(default_factory=list)
    maps: MapSettings = field(default_factory=MapSettings)
    gate: GateSettings = field(default_factory=GateSettings)
    require_pinned_revisions: bool = True
    eval_split: str = "test"
    eval_max_examples: int | None = None
    control_tasks: list[str] = field(default_factory=list)
    alt_templates: list[str] = field(default_factory=list)  # robustness prompt formats
    fewshot: FewShotSettings = field(default_factory=FewShotSettings)
    artifacts_dir: str = "artifacts"
    results_dir: str = "results"
    data_dir: str = "data"

    def validate(self) -> None:
        names = [b.name for b in self.bases]
        if len(set(names)) != len(names):
            raise ConfigError("duplicate base names")
        for b in self.bases:
            b.validate(require_pinned=self.require_pinned_revisions)
        ids = [t.task_id for t in self.tasks]
        if len(set(ids)) != len(ids):
            raise ConfigError("duplicate task ids")
        for t in self.tasks:
            t.validate()
        self.lora.validate()
        self.train.validate()
        for s in self.splits:
            unknown = set(s.holdout) - set(ids)
            if unknown:
                raise ConfigError(f"split {s.split_id}: unknown holdout tasks {sorted(unknown)}")
            if not s.holdout or len(s.holdout) >= len(ids):
                raise ConfigError(f"split {s.split_id}: need >=1 holdout and >=1 training task")
        if not self.seeds:
            raise ConfigError("at least one seed is required")
        unknown_controls = set(self.control_tasks) - set(ids)
        if unknown_controls:
            raise ConfigError(f"unknown control tasks {sorted(unknown_controls)}")
        if self.gate.primary_method not in self.gate.learned_methods:
            raise ConfigError("gate.primary_method must be one of gate.learned_methods")
        if self.gate.baseline not in {"fewshot", "zeroshot"}:
            raise ConfigError("gate.baseline must be fewshot|zeroshot")
        if self.gate.baseline == "fewshot" and self.fewshot.k <= 0:
            raise ConfigError("gate.baseline: fewshot needs fewshot.k > 0")

    def base(self, name: str) -> BaseConfig:
        for b in self.bases:
            if b.name == name:
                return b
        raise KeyError(name)

    def task(self, task_id: str) -> TaskConfig:
        for t in self.tasks:
            if t.task_id == task_id:
                return t
        raise KeyError(task_id)

    def path(self, kind: str) -> Path:
        return resolve_path({"artifacts": self.artifacts_dir, "results": self.results_dir,
                             "data": self.data_dir}[kind])


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def resolve_path(p: str | Path, relative_to: Path | None = None) -> Path:
    p = Path(p)
    if p.is_absolute():
        return p
    if relative_to is not None and (relative_to / p).exists():
        return (relative_to / p).resolve()
    return (REPO_ROOT / p).resolve()


def read_config_file(path: str | Path) -> dict[str, Any]:
    path = resolve_path(path)
    text = path.read_text()
    if path.suffix == ".json":
        data = json.loads(text)
    else:
        data = yaml.safe_load(text)
    if not isinstance(data, dict):
        raise ConfigError(f"{path}: top level must be a mapping")
    data.setdefault("_path", str(path))
    return data


def _from_dict(cls, data: dict[str, Any]):
    names = {f.name for f in dataclasses.fields(cls)}
    unknown = set(data) - names - {"_path", "kind"}
    if unknown:
        raise ConfigError(f"{cls.__name__}: unknown fields {sorted(unknown)}")
    return cls(**{k: v for k, v in data.items() if k in names})


def _load_ref(ref: str | dict[str, Any], cls, base_dir: Path | None):
    if isinstance(ref, (str, Path)):
        data = read_config_file(resolve_path(ref, base_dir))
    else:
        data = dict(ref)
    return _from_dict(cls, data)


def load_base(ref, base_dir: Path | None = None) -> BaseConfig:
    return _load_ref(ref, BaseConfig, base_dir)


def load_task(ref, base_dir: Path | None = None) -> TaskConfig:
    t = _load_ref(ref, TaskConfig, base_dir)
    t.validate()
    return t


def load_lora(ref, base_dir: Path | None = None) -> LoraSettings:
    s = _load_ref(ref, LoraSettings, base_dir)
    s.validate()
    return s


def load_train(ref, base_dir: Path | None = None) -> TrainSettings:
    s = _load_ref(ref, TrainSettings, base_dir)
    s.validate()
    return s


def load_experiment(path: str | Path, allow_unpinned: bool = False) -> ExperimentConfig:
    data = read_config_file(path)
    base_dir = Path(data["_path"]).parent
    exp = ExperimentConfig(
        name=data["name"],
        bases=[load_base(b, base_dir) for b in data["bases"]],
        tasks=[load_task(t, base_dir) for t in data["tasks"]],
        lora=load_lora(data.get("lora", {}), base_dir),
        train=load_train(data.get("train", {}), base_dir),
        seeds=list(data["seeds"]),
        splits=[HoldoutSplitSpec(**s) for s in data.get("splits", [])],
        maps=_from_dict(MapSettings, data.get("maps", {})),
        gate=_from_dict(GateSettings, data.get("gate", {})),
        fewshot=_from_dict(FewShotSettings, data.get("fewshot", {})),
        **{k: data[k] for k in ("require_pinned_revisions", "eval_split", "eval_max_examples",
                                "control_tasks", "alt_templates", "artifacts_dir", "results_dir", "data_dir")
           if k in data},
    )
    if allow_unpinned:  # inspection only (e.g. `uag validate --allow-unpinned`); never for launching
        exp.require_pinned_revisions = False
    exp.validate()
    return exp


def to_dict(obj) -> dict[str, Any]:
    return dataclasses.asdict(obj)


def dump_yaml(data: dict[str, Any], path: str | Path) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    data = json.loads(json.dumps(data, default=str))  # plain types only (e.g. TorchVersion -> str)
    Path(path).write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True))
